"""Convert a Hershey .jhf font file into game/render/hershey_data.py.

Usage: python tools/hershey_convert.py futural.jhf > game/render/hershey_data.py

The .jhf files (e.g. from https://github.com/kamalmostafa/hershey-fonts) hold
glyphs in ASCII order starting at space. Each record is a 5-char id, a 3-char
vertex count, then coordinate pairs encoded as characters relative to 'R'.
The first pair is the glyph's left/right extent; " R" lifts the pen.
Long records may wrap onto following lines.
"""

import sys

HEADER = '''"""Hershey Roman Simplex stroke font, ASCII 32-126. Generated by tools/hershey_convert.py.

The Hershey Fonts were originally created by Dr. A. V. Hershey while working
at the U. S. National Bureau of Standards.
The format of the Font data in this distribution was originally created by
James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821
(mit-eddie!ci-dandelion!hurt).

GLYPHS maps a character to (left, right, strokes); each stroke is a tuple of
(x, y) points in font units, y pointing down, baseline at BASELINE.
"""

'''


def read_records(text):
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        i += 1
        if not line.strip():
            continue
        count = int(line[5:8])
        body = line[8:]
        while len(body) < count * 2 and i < len(lines):
            body += lines[i]
            i += 1
        yield body[: count * 2]


def parse(body):
    def val(c):
        return ord(c) - ord("R")

    left, right = val(body[0]), val(body[1])
    strokes, current = [], []
    for p in range(2, len(body), 2):
        pair = body[p : p + 2]
        if pair == " R":
            if current:
                strokes.append(tuple(current))
            current = []
        else:
            current.append((val(pair[0]), val(pair[1])))
    if current:
        strokes.append(tuple(current))
    return left, right, tuple(strokes)


def main(path):
    with open(path, encoding="ascii") as f:
        records = list(read_records(f.read()))
    out = [HEADER, "BASELINE = 9\n", "GLYPHS = {\n"]
    for index, body in enumerate(records):
        left, right, strokes = parse(body)
        out.append(f"    {chr(32 + index)!r}: ({left}, {right}, {strokes!r}),\n")
    out.append("}\n")
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
